### ISSUE TITLE
MSIE8 + testing

### ISSUE THREAD

**Issue by jathayde** [meticulous/state-decoded-ui-2012#11]

**Comment by jalbertbowden** [comment]
i guess since it's assigned i'll back off....i'm new to actively participating on github. quick glance in ie10 and footer width is off. adding width 100% fixed that. didn't view in other browsers, so if that's not desirable, you can add conditional comments for ie10 via js, gist: https://gist.github.com/jalbertbowden/5174156  demo: http://dev.bowdenweb.com/ua/browsers/ie/ie10-detection-via-cc.html   sorry if this isn't the correct way to do things. n00b here.

**Comment by jathayde** [comment]
We're just cranking through to get this over to Waldo and Bill so they can integrate it and release 0.7.

**Comment by lynnwallenstein** [comment]
Tested through browser stack on IE 8, 9 and 10 - Bunch of small fixes (clearing float etc). This will probably need to be retested once you integrate it into working code.
